version: "3.7"
services:
  keycloak:
    container_name: keycloak
    image: jboss/keycloak
    ports:
      - "8180:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/quarkus-realm.json
    volumes:
      - ./configurations/realm/quarkus-realm.json:/tmp/quarkus-realm.json
